#!/usr/bin/perl
#Landru, David Ferrone, Jan 25 2015
#Update May 2017. One file, new library, attach one image.
# # # # # # # # # # # # # # # # # #
# We first produce the text file Landru_Commands.txt (for no real reason). Then mail that text out, along with a snazzy jpeg.
use Email::Sender::Transport::SMTP qw();
use Email::Stuffer;
use Email::Send::SMTP::Gmail;
######### Edit These ########################
my $Gmail_Option=1;		  # mark as 0 to NOT use gmail
my $Name_One="Person One";
my $Name_Two="Person Two";
my $Receivers='receiver1@gmail.com, receiver2@gmail.com';
my $Sender='Username@gmail.com';
my $Passwd='password';
# SMTP and port are actually hard-coded if gmail_option is on.
# Edit these next two lines if you have a different mail server.
my $SMTP_Address='smtp.gmail.com'; 
my $PORT_Num='465'; # e.g. gmail ssl port
my @Chore_List=("Kitchen", "Bathroom", "Living room", "Dining room","Bedroom","Laundry");
my $output_filename = "Landru_Commands.txt";
my $image_filename = "LandruProjection.jpg";
my $subject = "... Chores ...";
#############################################
########## No Need to Change Code Below #####
## (Formerly chores.pl)
my @Local_List = @Chore_List;
sub Chore_Selector{
    my $Half_Length = int($#Local_List/2);
    my $Chores="";
    for (my $i=0; $i <= $Half_Length; $i++) {
	my $Length = $#Local_List;
	my $r = rand($Length);
	$Chores=$Chores.$Local_List[$r].", ";
	splice @Local_List, $r, 1;
    }
    return $Chores;
}
sub Chores {
    my $Selected_Chores = Chore_Selector();
    my $OUTPUT;
    $OUTPUT .= "The chores I have selected for $Name_One are: ".$Selected_Chores."\n\n";
    $OUTPUT .= "The chores I have selected for $Name_Two are: ";
    foreach (@Local_List) {
	$OUTPUT .= $_.", ";
    }
    $OUTPUT .= "\n\n";
    return $OUTPUT;
}
############################################################
## Formerly mailer.pl
sub SendIt{
    # Doesn't like no msg! We will read from a text file.
    open (my $FH, "<", $output_filename);
    my @MSG = <$FH>;
    close $FH;
    my $transport = Email::Sender::Transport::SMTP->new({
	host => $SMTP_Address,
	port => $PORT_Num,
	sasl_username => $Sender,
	sasl_password => $Passwd,
    });

    Email::Stuffer->to( $Receivers )
	  ->from($Sender)
	  ->subject($subject)
	  ->text_body("@MSG")
	  ->attach_file($image_filename)
	  ->transport($transport)
	  ->send;    
}
sub Gmail_SendIt {
    open (my $FH, "<", $output_filename);
    my @MSG = <$FH>;
    close $FH;

    my $mail=Email::Send::SMTP::Gmail->new( -smtp=>'smtp.gmail.com',
					    -layer=> 'ssl',
					    -port=>465,
					    -login=>$Sender,
					    -pass=>$Passwd
					);

    $mail->send(-to=>$Receivers,
		-subject=>$subject,
		-verbose=>'1',
		-body=>"@MSG",
		-attachments=>$image_filename,
	    );

    $mail->bye;
}
############################################################
## Formerly Landru_Quote.pl
sub PrintIt{
    if (-e $output_filename) {
	unlink $output_filename;
    }
    open (my $FH, ">>", $output_filename);
    my $a_result = Chores();    
    print $FH "Hark! THIS IS THE WORD OF LANDRU...\nYou are compelled to obey.\n\n";
    print $FH $a_result;
    print $FH "If these chores are not completed within one week...\n\t the offender will be absorbed.\n";
    print $FH "\t\t\t For the good of the body and all that. \n\n\t\t\t\t ta ta for now, Landru\n";
    print $FH "\n -- \n";
    print $FH "Landru seeks tranquility. Peace for all. The universal good.\n";
}

PrintIt();

if ($Gmail_Option) {
    Gmail_SendIt();
} elsif (!$Gmail_Option) {
    SendIt();
}
